import { CREDENTIAL, PRESENTATION } from "./actionTypes"

export const ALL_FILTER_INDEX = 0

export const FILTER_HISTORIC = {
    [PRESENTATION.REVOKE.TYPE]: PRESENTATION.REVOKE.DESCRIPTION,
    [PRESENTATION.ACCESS.TYPE]: PRESENTATION.ACCESS.DESCRIPTION,
    [CREDENTIAL.SAVE.TYPE]: CREDENTIAL.SAVE.DESCRIPTION
  }